# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
title:            Structural
description:      'film soul-delay bridge dead alcohol skyscraper city boat pre- rain car assault sprawl semiotics wonton soup savant. construct '
url:              http://structur.al
baseurl:          /

paginate:         5

default_image:    'bridge.jpg'

social_links:
  - url:  http://twitter.com/structuralists
    icon: twitter
  - url:  http://github.com/structural
    icon: github
  - url: /atom.xml
    icon: rss
